version: '3.3'
services:
    tyk-dashboard:
        image: tykio/tyk-dashboard:v5.2rc2
        container_name: tyk-dashboard
        ports:
            - "3000:3000"
            - "5000:5000"
            - "1026:1025"
        environment:
            - "TYK_DB_LICENSEKEY=${TYK_DB_LICENSEKEY}"
            - TYK_LOGLEVEL=${TYK_LOGLEVEL:-debug}
        volumes:
            - ./conf/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
            - ./conf/tyk_analytics.conf:/develop/confs/tyk_analytics.conf
        depends_on:
            - tyk-redis
            - tyk-mongo
            - tyk-gateway
    tyk-gateway:
        image: tykio/tyk-gateway:v5.2rc2
        container_name: tyk-gateway
        ports:
            - "6000:6000"
            - "8003:8003"
            - "8080:8080" 
        volumes:
            - ./conf/tyk.conf:/opt/tyk-gateway/tyk.conf
            - ./conf/tyk.conf:/develop/confs/tyk.conf
            - ./conf/cert.pem:/etc/ssl/certs/cert.pem
            - ./conf/key.pem:/etc/ssl/certs/key.pem
            - ./apps:/opt/tyk-gateway/apps
            - ./middleware:/opt/tyk-gateway/middleware
        environment:
            - TYK_LOGLEVEL=info
        depends_on:
            - tyk-redis            
    tyk-redis:
        image: redis:6.2
        ports:
            - "6379:6379"
    tyk-mongo:
        image: mongo:4.1
        ports:
            - "27017:27017"
    federation:
        container_name: federation
        image: agatawitkowska/federation-example
        ports:
            - "4000:4000"
            - "4001:4001"
            - "4002:4002"
            - "4003:4003"    
