version: '3.3'
services:
    tyk-gateway:
        image: tykio/tyk-gateway:v3.2.1
        ports:
            - "6000:6000"
            - "8003:8003"
            - "8080:8080" 
        volumes:
            - ./conf/tyk_pro.conf:/opt/tyk-gateway/tyk.conf
            - ./conf/cert.pem:/etc/ssl/certs/cert.pem
            - ./conf/key.pem:/etc/ssl/certs/key.pem
            - ./apps:/opt/tyk-gateway/apps
            - ./middleware:/opt/tyk-gateway/middleware
        environment:
            - TYK_LOGLEVEL=info
            - TYK_GW_DBAPPCONFOPTIONS_CONNECTIONSTRING=\${/sbin/ip route|awk '/default/ { print $3 }'}
            - TYK_GW_POLICIES_POLICYCONNECTIONSTRING=\${/sbin/ip route|awk '/default/ { print $3 }'}
        depends_on:
            - tyk-redis
    tyk-pump:
        image: tykio/tyk-pump-docker-pub:latest
        volumes:
            - ./conf/pump.conf:/opt/tyk-pump/pump.conf
        ports:    
            - "8061:8061"
        depends_on:
            - tyk-redis
            - tyk-mongo
            - tyk-gateway
    tyk-redis:
        image: redis:6
        ports:
            - "6379:6379"
    tyk-mongo:
        image: mongo:4.1
        ports:
            - "27017:27017"